### ISSUE TITLE
Add "error" log level

### ISSUE THREAD

**Issue by GianLorenzetto** [cake-contrib/Cake.Npm#11]
I think the "error" log level is missing from NpmLogLevel.

Although it has no shortcut option (e.g. -d) it is a valid value when passed to the long from of --loglevel (at least on Windows).

Cheers,
Gian

**Comment by giblet75** [comment]
Do you have an example of a cake script with it in there? I couldn't use the Enum in my script - it was not resolving.

**Comment by Philo** [comment]
@giblet75 - the `readme.md` and `usage.cake` files in the repo have usage examples.

I will look to add the error loglevel in the next maintenance release.

Apologies for the delay in my replies.
