### ISSUE TITLE
Unformatted layout with webpack

### ISSUE THREAD

**Issue by taconaut** [cake-contrib/Cake.Npm#112]
I'm automating some build steps with cake.

When running following target:
```
Task ("Npm-Build")
    .Does (() => {
        var settings = new NpmRunScriptSettings {
            ScriptName = "build",
            WorkingDirectory = frontendDir
        };

        NpmRunScript (settings);
        Information ($"Executed 'npm run build' for frontend located in '{frontendDir}'");
    });
```

The webpack output is all over the place:
![image](https://user-images.githubusercontent.com/275379/84375569-0ef23600-abe0-11ea-8d6a-2eb2b0bf4bbf.png)

When running the `npm run build` the ouput is fine:
![image](https://user-images.githubusercontent.com/275379/84375621-29c4aa80-abe0-11ea-8938-90d7e5f9f671.png)

How can I get a clean and readable outpur using Cake.Npm?

**Comment by gep13** [comment]
@taconaut can you please confirm what version of Cake and Cake.Npm you are using? Thanks

**Comment by taconaut** [comment]
Hi @gep13 I'm using the latest `Cake.Npm`: `#addin nuget:?package=Cake.Npm&version=0.17.0`
Where is the cake version defined? I'm using the same bootstrapper script as [this](https://github.com/taconaut/Sppd.TeamTuner/blob/master/build.ps1) and the file version of `Cake.Common.dll` found in the tools folder created when running the script is 0.38.2.0

**Comment by gep13** [comment]
@taconaut you typically pin to a specific version of Cake by specifying what version you want to use in the packages.config file in the tools folder.  You can see an example here:

https://github.com/cake-contrib/Cake.Gem/blob/develop/tools/packages.config#L3

Do you know if this has always been like this, in earlier versions of Cake, or are you new this recently and just noticed it?

**Comment by taconaut** [comment]
@gep13 I hadn't used this build constellation before. But I've now tried older versions. The formatting is good until (and including) 0.37.0; with 0.38.0 it breaks.
I'll reference 0.37.0 for now (as you've shown me how I can do this :))

**Comment by gep13** [comment]
@taconaut thank you for confirming that!

@patriksvensson @devlead looks like this is a candidate for changes related to the ANSI escape codes which were added in 0.38.0.

**Comment by devlead** [comment]
@taconaut except losing colors does it format correctly if you execute something like below?
```PowerShell
.\build.ps1 --Target=Npm-Build | Out-String
```

**Comment by taconaut** [comment]
@devlead yes it does

**Comment by taconaut** [comment]
After updating to cake 1.1.0 and cake.npm 1.0.0 I didn't encounter this issue anymore
