### ISSUE TITLE
CakeBuild Experimental mode (Rosyln C# 6) breaks WithLogLevel()

### ISSUE THREAD

**Issue by dennisroche** [cake-contrib/Cake.Npm#13]
This is more as a Public Service Announcement than an issue.

If you enable `Experimental` mode in Cake to get some of lovely C# 6 features, you will get the following error for:

``` csharp
Npm.WithLogLevel(NpmLogLevel.Silent).Install();
```

``` csharp
error CS1061: 'INpmRunnerConfiguration' does not contain a definition for 'Install' and     
no extension method 'Install' accepting a first argument of type 'INpmRunnerConfiguration'     
could be found (are you missing a using directive or an assembly reference?)
```

Workaround, you need to cast the `INpmRunnerConfiguration` to `NpmRunner`.

``` csharp
((NpmRunner)Npm.WithLogLevel(NpmLogLevel.Silent)).Install();
```

**Comment by Philo** [comment]
Firstly apologies for the delay in replying to your issue, "real life" has been hectic the past few weeks.

After implementing the recent `.WithLogLevel` and `.FromPath` options I realised I wasnt correctly covering the possible usage very well, leading to this issue.  I am planning to find a way to update the addin while maintaining backwards compatibility.

In the mean time another workaround is to chain the `.FromPath` whenever using `.WithLogLevel`.

```c#
  Npm.WithLogLevel(NpmLogLevel.Silent).FromPath(".").Install();
```

**Comment by dennisroche** [comment]
@Philo no problem, "real life" is more important than this issue. 

If you want help with fixing this, let me know. I'm happy to jump in.
