### ISSUE TITLE
Problem when running cake.npm in WSL

### ISSUE THREAD

**Issue by sjetha** [cake-contrib/Cake.Npm#133]
Hi. I have a WSL installation where I can run NPM commands without issue from the command line, but if I try to use cake.npm to run my commands, it finds the Windows version of NPM and tries to run that in the Linux environment.
I can work around the problem by removing the Windows paths from $PATH, but I can't understand why it runs ok from the command line but doesn't run properly when using cake.npm.

Here is a snippet of the diagnostic output when running cake.npm's run-script command:
```
Executing task: Default
Using addin: Cake.Npm v0.0.0.0 ([NULL])
npm arguments: run-script --loglevel verbose "build"
Resolved tool to path /mnt/c/Program Files/nodejs/npm.cmd
Executing: /mnt/c/Program Files/nodejs/npm.cmd run-script --loglevel verbose "build"
```

**Comment by sjetha** [comment]
@gep13 @devlead

**Comment by sjetha** [comment]
Here is the output if I set PATH to `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib`:
```
Executing task: Default
Using addin: Cake.Npm v0.0.0.0 ([NULL])
npm arguments: run-script --loglevel verbose "build"
Could not resolve path for tool "npm.cmd" using these directories: /usr/local/sbin,/usr/local/bin,/usr/sbin,/usr/bin,/sbin,/bin,/usr/games,/usr/local/games,/usr/lib/wsl/lib
Resolved tool to path /usr/bin/npm
Executing: /usr/bin/npm run-script --loglevel verbose "build"
```

**Comment by pascalberger** [comment]
Updating the path is the correct workaround for the time being. Cake 1.1 will improve tool detection in this case https://github.com/cake-build/cake/issues/3066
