### ISSUE TITLE
Error: Failed to install addin 'Cake.Npm'

### ISSUE THREAD

**Issue by vijayakarunakar** [cake-contrib/Cake.Npm#140]
we are getting below error message for cake.npm, we are using .NETFramework,Version=v4.8. Please help on this ASAP.

Could not find any assemblies compatible with .NETFramework,Version=v4.6.1.
Cake.exe : Error: Failed to install addin 'Cake.Npm'.
At build.ps1:233 char:1
+ &$CAKE_EXE $cakeArguments
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: Failed t...din 'Cake.Npm'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by nils-a** [comment]
@vijayakarunakar sorry to hear you are having problems, can you please provide the version of Cake you are using and the version of Cake.Npm?

**Comment by vijayakarunakar** [comment]
we are using cake version as 0.38.2, we have latest cake.npm and other lower version but it's not working.
PFB package.config 

Package.config
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Cake" version="0.38.2" />
</packages>

**Comment by nils-a** [comment]
For Cake versions 0.x you need to use Cake.Npm version 0.17.0. (Cake.Npm version 1.0.0 requires Cake version 1.0.0 or later and Cake.Npm version 2.0.0 requires Cake version 2.0.0)

Keep in mind that need to clean `./tools/Addins` if you switch the version of the addin, else the "old" versions will still be around and Cake will try to load them.

**Comment by vijayakarunakar** [comment]
Thanks for the response. 
we are now using  Cake.Npm version 0.17.0(Command as mentioned below) and cake version as 0.38.2. when we execute there are two cake.npm and cake.npm.0.17.0 folders getting generated in \tools\Addins folder and finally we are getting the error as Error: Failed to install addin 'Cake.Npm'.

In build.cake file we have added the cake.npm as:
#addin nuget:https://api.nuget.org/v3/index.json?package=Cake.npm&version=0.17.0

**Comment by nils-a** [comment]
Would you be able to share an example project that reproduces the error?

**Comment by nils-a** [comment]
@vijayakarunakar I have created a small demo at https://github.com/nils-a-demos/cake-npm-140 - this project uses the old bootstrapper to ensure a .NET Framework version of Cake. The version is pinned to Cake 0.38.2. It then loads Cake.Npm in version 0.17.0 and runs a simple `npm version` command. 

Everything works flawlessly. Does that project produce the same error as your project?

**Comment by vijayakarunakar** [comment]
@nils-a Thanks for sharing the demo project, that was working fine without any issues. I compared build.cake files with our project. we have below Cake.Sitecore nuget when we add these in demo project which you shared we will be able to replicate the issue.  
#tool nuget:?package=Cake.Sitecore&version=1.0.3
#load nuget:?package=Cake.Sitecore&version=1.0.3

**Comment by nils-a** [comment]
@vijayakarunakar yes, Cake.Sitecore, in version 1.0.3 seems to load Cake.Npm without an explicit version being set. This will result in the newest version (currently 2.0.0) being downloaded.

The current version of Cake.Sitecore - 1.0.27 seems to have that problem fixed.

**Comment by JDTechNet** [comment]
how can we check what is the version of cake is being used?

we are using [1.0.0](https://www.nuget.org/packages/Cake.Npm/1.0.0) and teamcity is able to build the code successfully.
But, Angular application is not working in IE11 after this build. if we build in local and deploy to staging environment - it seems working. 

SCRIPT5017: Syntax error in regular expression
polyfills-es5...........................js

**Comment by nils-a** [comment]
You can run `cake.exe --info` or `cake.exe --version` to see the version.

You can also use `--verbosity=diagnostic` during builds to see real verbose output of what is happening.

**Comment by vijayakarunakar** [comment]
@nils-a After using current version of Cake.Sitecore - 1.0.27 it is working. Thank you.

**Comment by vijayakarunakar** [comment]
After using current version of Cake.Sitecore - 1.0.27 it is working. Thank you.
