### ISSUE TITLE
Add support for Npm.Publish

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Npm#20]
Support for the `npm publish` command would be nice.

**Comment by pascalberger** [comment]
@FlorianHockmann Are you interested in testing? There is a version available [here](https://ci.appveyor.com/project/cakecontrib/cake-npm/build/0.9.3-PullRequest0037.2%7C39/artifacts) which contains an `NpmPublish` alias.

**Comment by FlorianHockmann** [comment]
@pascalberger I just tried it out and from the first impression it looks good, but I'm missing an option to specify the registry as I don't want my package to be published to the default registry. A property in the respective settings for the registry would be helpful. Currently I am simply issuing the following command from PowerShell:
`npm publish $package --registry $registryUrl`

**Comment by pascalberger** [comment]
@FlorianHockmann I added a `Registry` parameter to the settings class which alows to add the `--registry` parameter. A new test build is available [here](https://ci.appveyor.com/project/cakecontrib/cake-npm/build/0.9.3-PullRequest0037.12%7C54/artifacts).

**Comment by FlorianHockmann** [comment]
Thanks @pascalberger, I just tried the test build and it works as expected :-)

**Comment by pascalberger** [comment]
@FlorianHockmann It's now released: https://www.nuget.org/packages/Cake.Npm/0.10.0

Including support for `--tag`, `--access` parameters and a fluent syntax for generating the settings object.
