### ISSUE TITLE
Clean up use of interfaces in NpmRunner

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Npm#21]
The use of the `INpmRunnerCommands` and `INpmRunnerConfiguration` interfaces seems to be quite inconsistent. 

While `INpmRunnerConfiguration.FromPath` returns an `INpmRunnerCommands`, `INpmRunnerConfiguration. WithLogLevel` returns an `INpmRunnerConfiguration`. IMHO it should be possible to write either `Npm.FromPath("C:\foo").WithLogLevel(NpmLogLevel.Silent).Install()` or `Npm.WithLogLevel(NpmLogLevel.Silent).FromPath("C:\foo").Install()`.

Also it is not clear to me why the methods of `INpmRunnerCommands` return an `INpmRunnerCommands` object and not `void` or the output of the specific npm command?

One last thing is that there is an `NpmRunner.Pack`, but no `INpmRunnerCommands.Pack`, which makes it impossible to use with the `INpmRunnerConfiguration` functions.

If there's interested in having this cleaned up I can write a PR.

**Comment by Philo** [comment]
Hi @pascalberger, I totally agree with your assessment on the inconsistency of the fluent interfaces after the introduction of `WithLogLevel`, The fluent style could do with some re-work, if you already have code to this end I'll gladly accept a PR for review.
