### ISSUE TITLE
Add support for npm-cache

### ISSUE THREAD

**Issue by bravecobra** [cake-contrib/Cake.Npm#26]
As Cake.Npm is often run on build servers, adding support for npm-cache sounds logical. 

https://www.npmjs.com/package/npm-cache

Since npm-cache is just a wrapper around npm|bower|composer|jspm, it would rather easy to implement by just 
```
protected override IEnumerable<string> GetToolExecutableNames()
{
      yield return "npm-cache.cmd";
      yield return "npm-cache";
      yield return "npm.cmd";
      yield return "npm";
}
``` 
On my machine that would improve the speed of running `npm(-cache) install` from 6 minutes down to 1 min 15 secs on the second run provided that my package.json hasn't changed.

**Comment by agc93** [comment]
Overriding the executable name is not the right solution here as, although it's a wrapper, `npm-cache`'s command line behaviour is not the same as `npm`s. If it was included in Cake.Npm, it should probably be a new high-level alias. The problem there is that it won't necessarily be installed even with `npm` installed..

**Comment by bravecobra** [comment]
I see your point there on the installation part. Maybe making it a high level alias might indeed be a better solution. Checking for the existence of the tool and spitting out an error if it isn't, doesn't seem like a problem to me. I can imagine that running Cake.Npm without having npm installed, is probably doing the same thing.

**Comment by bravecobra** [comment]
I've did a couple of tests and while a simple "Install" works, it breaks lots of other stuff. It would take a whole separate Runner to support this.

**Comment by agc93** [comment]
Yes but having Cake.Npm throw errors when npm is not there is expected given its a wrapper for `npm`. Is there any reason not to have a Cake.NpmCache add-in for example? Maybe @philo wants to chime in here, but for the same reason as Gulp, Grunt and Webpack getting their own add-ins it seems like `npm-cache` probably should: especially given it actually supports more than just `npm`

**Comment by bravecobra** [comment]
I'm starting to think the same thing

**Comment by Philo** [comment]
Sounds like a perfect opportunity for @bravecobra you build an addin ;)

I would prefer to keep this addin focused on tasks issued via the "npm" command itself.  If there are no objections to this I'll close this issue.

**Comment by bravecobra** [comment]
Sure. Seems than reasonable.
