### ISSUE TITLE
Add option to use `npm set` and `npm adduser`

### ISSUE THREAD

**Issue by bravecobra** [cake-contrib/Cake.Npm#27]
It sounds reasonable to be able to use `npm set` on build servers. I'd like for instance to be able to disable the progress just before running npm install as that would improve the speed significantly. Having an extra cake command to use "npm set", would enable us to configure the npm settings on the build server. 

http://biercoff.com/how-to-crazy-easily-speed-up-your-npm-install-speed/

This would also allow for setting the registry to be used on the build server/agent for npm to use. Of course you would need a login command there as well ;)

**Comment by Philo** [comment]
Moved adduser request to #78
