### ISSUE TITLE
Update to latest Cake.Core

### ISSUE THREAD

**Issue by Philo** [cake-contrib/Cake.Npm#29]
As of writing this is v0.19.3

**Comment by pascalberger** [comment]
@Philo Is there a need for updating? Since this will require all users of the addin to also move to the latest Cake version. Instead I would suggest to build against 0.16.2, which is the minimum required version for the latest Cake version.

**Comment by pascalberger** [comment]
Ah, just remembered that Cake 0.18 would be a requirement for https://github.com/cake-contrib/Cake.Npm/pull/23. But instead of going to 0.19.3 I would suggest to build against 0.18.

**Comment by Philo** [comment]
OK, can downgrade to 0.18 :)
