### ISSUE TITLE
Update to msbuild15 and new csproj system

### ISSUE THREAD

**Issue by Philo** [cake-contrib/Cake.Npm#30]
This will also implement the addin for both `netstandard1.6` and `net46`

**Comment by gep13** [comment]
@Philo be interested to see how this goes, and what changes you make to the existing build.cake file.

Would be very interested to bring these changes into Cake.Recipe.

**Comment by Philo** [comment]
First huddle:

```
Installing addins...
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.Npm'.
```

Need to update project targets to include `net452`.

**Comment by gep13** [comment]
@Philo yes, and that fits with what @patriksvensson suggested in the Slack Channel.
