### ISSUE TITLE
Latest version breaks build

### ISSUE THREAD

**Issue by trailmax** [cake-contrib/Cake.Npm#32]
With the latest NuGet v0.9.0 we have started getting compile time error 

> The name 'Npm' does not exist in the current context

If I specify v0.8.0 in the cake script, it works just fine: `#addin "nuget:?package=Cake.Npm&version=0.8.0"`

So something is broken with the latest release.

**Comment by pascalberger** [comment]
There are some breaking changes in Cake.Npm 0.9.0. See [release notes](https://github.com/cake-contrib/Cake.Npm/releases/tag/0.9.0) for details and how to migrate.

**Comment by trailmax** [comment]
Are you planning to update the documentation/samples further? I'm getting issues with sample from readme.md

**Comment by trailmax** [comment]
Apologies. That was incorrect version of NuGet stuck in cache. Ignore my previous comment.
