### ISSUE TITLE
Passing invalid logLevel argument after migration to 0.9.0

### ISSUE THREAD

**Issue by Lowcase** [cake-contrib/Cake.Npm#34]
My original cake script for executing eslint task in package.json was:
```
Npm.FromPath("./Frontend/").RunScript("eslint -- -f html -o ./../reports/eslint.html");
```
To make it compatible with version 0.9.0 I changed it to this:
```
var settings = new NpmRunScriptSettings()
{
	WorkingDirectory = "./Frontend/",
	ScriptName = "eslint"
};
settings.Arguments.Add("-f html");
settings.Arguments.Add("-o ./../reports/eslint.html");
NpmRunScript(settings);
```

Now the script will fail during the run time with following error.
```
========================================
RunEslintFrontend
========================================
Executing task: RunEslintFrontend
Using addin: Cake.Npm v0.9.0.0 (0.9.0+Branch.master.Sha.41a1dc81c79996314343b2f8ef8840581ac56f36)
npm arguments: run-script "eslint" -- -f html -o ./../reports/eslint.html --loglevel info

> app-react@1.0.0 eslint D:\git\Engage\Frontend
> eslint . --ext .js --ext .jsx "-f" "html" "-o" "./../reports/eslint.html" "--loglevel" "info"

Invalid option '--loglevel' - perhaps you meant '--global'?
```
If I understand it correctly the `--loglevel info` should be before the double dash to be recognized as argument for npm itself. Now it is sent to underlying command (eslint in my case).

**Comment by Philo** [comment]
v0.9.2 is currently building and will be available on nuget in the next 5-10 minutes.  Can you please confirm whether this corrects your issue.

https://github.com/cake-contrib/Cake.Npm/releases/tag/0.9.2

Cheers

**Comment by Lowcase** [comment]
Thank you for a quick fix. It is not working correctly.
