### ISSUE TITLE
Switch to GitFlow

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Npm#35]
In preparation for moving to Cake.Recip (#18) it would be helpful to change Git workflow to GitFlow as most projects in the cake-contrib organization are using.

**Comment by bergmeister** [comment]
As far as I understand, this can only be done by someone with sufficient admin rights on this repository.
But at the end all you need to do is run `git flow init` and answer the questions (or you use `git flow init -d` to use the defaults, which should be OK). At the end it will create you a `develop` branch that you then push.

**Comment by pascalberger** [comment]
@bergmeister Creation of the `develop` branch is not the big issue here. The build process needs to also be adopted  (can be done by using Cake.Recipe #18)

**Comment by bergmeister** [comment]
Sorry for the late response. I see what you mean. Sorry, I don't think that is the kind of thing that interests me.
