### ISSUE TITLE
Use same issue labels as other cake-contrib projects

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Npm#36]
Most project in the cake-contrib organization use the following issue labels:

- Breaking change
- Bug
- Build
- Documentation
- Feature
- Improvement
- Up-for-grabs

We should consider to also switch to use the same labels

**Comment by gep13** [comment]
@pascalberger I am some code that will do this work for you 😄

**Comment by pascalberger** [comment]
@Philo OK, for you if we switch to the above mentioned labels?

**Comment by Philo** [comment]
yea, no issues with that

**Comment by gep13** [comment]
I can try to run the script to set them up tonight, if not it will be tomorrow.

**Comment by gep13** [comment]
@pascalberger @Philo this has now been done.

**Comment by pascalberger** [comment]
@gep13 Thanks!
