### ISSUE TITLE
Bring back possibility to run scripts from another path

### ISSUE THREAD

**Issue by perakerberg** [cake-contrib/Cake.Npm#38]
Hi,

In the previous version of Cake.Npm we used the fluent syntax to enable running scripts from a specific path. Like `Npm.FromPath("./SomeFolder").RunScript("some-script");`
We used this since our build uses two working folders, one installed with Production, one without.
In the 0.9.0 release, the fluent syntax is gone and I can't seem to figure out how to do that same operation given the new aliases. This was a great feature and bringing it back (or explaining how it is supposed to be done now) would be much appreciated.

Thanks!

**Comment by pascalberger** [comment]
You can set the working directory through the settings class like this:

```
var settings = 
    new NpmRunScriptSettings 
    {
        ScriptName = "some-script",
        WorkingDirectory = "./SomeFolder"
    };
NpmRunScript(settings);
```

**Comment by perakerberg** [comment]
Man that was fast! Somehow I missed the WorkingFolder property in those settings, but knowing about it made it really straight forward. Thanks for your help and the awesome work.

**Comment by pascalberger** [comment]
The `WorkingDirectory` property is [inherited from the ToolSettings class](http://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/A29EC283). Therefore easily can be missed without IntelliSense.

**Comment by perakerberg** [comment]
Indeed, I stopped digging at the add-in specific classes. Intellisense for Cake-files would be handy.

**Comment by pascalberger** [comment]
There's currently some work done for getting IntelliSense. See [this blog post](http://cakebuild.net/blog/2017/05/intellisense-and-intro).
