### ISSUE TITLE
Cake.Npm Failing to Install

### ISSUE THREAD

**Issue by JustinPullen** [cake-contrib/Cake.Npm#51]
It looks like Cake just pushed 0.22.0 so the addin is currently failing on install. 

Restoring NuGet package Cake.0.22.0.
  GET https://api.nuget.org/v3-flatcontainer/cake/0.22.0/cake.0.22.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/cake/0.22.0/cake.0.22.0.nupkg 128ms
Installing Cake 0.22.0.
Adding package 'Cake.0.22.0' to folder 'Path'
Added package 'Cake.0.22.0' to folder 'Path'
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Error: The assembly 'Cake.Npm, Version=0.11.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.18.0). 
This assembly need to reference at least Cake.Core version 0.22.0. 
Another option is to downgrade Cake to an earlier version. 
It's not recommended, but you can explicitly opt-out of assembly verification 
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true", 
envrionment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by Philo** [comment]
Hi @JustinPullen - there is a pull request that should be merged very soon that will support 0.22 - until then you will have to either pin your cake version or set the CAKE_SETTINGS_SKIPVERIFICATION variable.

**Comment by JustinPullen** [comment]
👍
