### ISSUE TITLE
Error: Failed to install addin 'Cake.Npm'.

### ISSUE THREAD

**Issue by epot** [cake-contrib/Cake.Npm#52]
Since yesterday, I am seeing strange issues when using this addin:

    Downloading NuGet.exe...
    Installing Cake...
    Running build script...
    Analyzing build script...
    Processing build script...
    Installing tools...
    Installing addins...
    Could not find any assemblies compatible with .NETFramework,Version=v4.5.
    Error: Failed to install addin 'Cake.Npm'.

**Comment by epot** [comment]
I just saw that 0.12.0 removed net45 support :)

**Comment by pascalberger** [comment]
@epot Cake removed support for .NET 4.5 in the latest version (see [here](https://cakebuild.net/blog/2017/09/cake-v0.22.0-released)) and version 0.12.0 of Cake.Npm was updated to support Cake 0.22.0. 
You can still use older versions of  Cake and Cake.Npm supporting .NET Framework 4.5 by [pinning versions](https://cakebuild.net/docs/tutorials/pinning-cake-version) (which you should do anyway to avoid having your build broken by a Cake or addin update).

**Comment by epot** [comment]
Yes, I did that, thanks :)
