### ISSUE TITLE
Unable to use .WithArguments as extension method

### ISSUE THREAD

**Issue by AlexCuse** [cake-contrib/Cake.Npm#67]
I have only seen this with the .WithArguments extension on NpmRunScriptSettings (https://github.com/cake-contrib/Cake.Npm/blob/develop/src/Cake.Npm/RunScript/NpmRunScriptSettingsExtensions.cs#L16-L31).  If I try to use it like so:

````
Task("JS-Tests")
	.IsDependentOn("NPM-Install")
	.DoesForEach(GetFiles("../root/*/karma.conf.js"), (suite) =>
	{
		var settings = new NpmRunScriptSettings { ScriptName = "test", WorkingDirectory = "../root" };
		
		settings = settings.WithArguments(suite).WithArguments(suite).WithArguments("--single-run");
			
		NpmRunScript(settings);
	});
````

I get the following error on script compilation:

> error CS1929: 'NpmRunScriptSettings' does not contain a definition for 'WithArguments' and the best extension method overload 'ProcessSettingsExtensions.WithArguments(ProcessSettings, Action<ProcessArgumentBuilder>)' requires a receiver of type 'ProcessSettings'

The only way around I have found is to define my task like so:

````
Task("JS-Tests")
	.IsDependentOn("NPM-Install")
	.DoesForEach(GetFiles("../root/*/karma.conf.js"), (suite) =>
	{
		var settings = new NpmRunScriptSettings { ScriptName = "test", WorkingDirectory = "../root" };
		
		settings = Cake.Npm.RunScript.NpmRunScriptSettingsExtensions.WithArguments(settings, suite.ToString());
		settings = Cake.Npm.RunScript.NpmRunScriptSettingsExtensions.WithArguments(settings, "--single-run");
			
		NpmRunScript(settings);
	});
````

Is there something special I need to do in my build script to use .WithArguments as an extension method?

**Comment by nils-a** [comment]
@AlexCuse the difference in your two examples ist one `ToString()`:

in the above example you write:
```
settings.WithArguments(suite)
```

while in the second example you write
```
Cake.Npm.RunScript.NpmRunScriptSettingsExtensions.WithArguments(settings, suite.ToString())
```

The first example fails, because the second param of `WithArguments` is a `string`, while `suite` is of type `FilePath`.

Soo.... If you add `ToString()` or better still `.FullPath` to your first example like so:

```
Task("JS-Tests")
	.IsDependentOn("NPM-Install")
	.DoesForEach(GetFiles("../root/*/karma.conf.js"), (suite) =>
	{
		var settings = new NpmRunScriptSettings { ScriptName = "test", WorkingDirectory = "../root" };
		
		settings = settings.WithArguments(suite.FullPath).WithArguments(suite.FullPath).WithArguments("--single-run");
			
		NpmRunScript(settings);
	});
```

 it should have worked.

**Comment by AlexCuse** [comment]
I just pointed it out because the rest of the plugins we were using seemed to offer overloads to more succinctly support this kind of looping.  I thought it looked pretty rough in context, and frequently needed to explain to developers that weren't familiar.

**Comment by AlexCuse** [comment]
You are right about the FullPath though should have used that 😀

**Comment by nils-a** [comment]
> [...] the rest of the plugins we were using seemed to offer overloads to more succinctly support this kind of looping. [...]

Can you give an example?

**Comment by AlexCuse** [comment]
I haven't been working on the project for a really long time now at this point sorry.  Not really doing any .net at all these days and haven't had a need to look at cake stuff for a couple years.  This package seems to have done just fine without the change thanks for making it available 😊

**Comment by nils-a** [comment]
@pascalberger I think this issue can be closed.
