### ISSUE TITLE
Support Cake 0.26.0

### ISSUE THREAD

**Issue by generik0** [cake-contrib/Cake.Npm#70]
Hi.
This morning the cake version with Cake.Npkm went out of sync. Please build and publish with latest cake.core :-)

**Comment by gep13** [comment]
@generik0 this is one of the many reasons that we recommend that you pin to a specific version of Cake, in your case 0.25.0.  If you don't "need" the new .Net Core 2.0 support in Cake 0.26.0, then I would recommend that you pin to an earlier version.

**Comment by pascalberger** [comment]
@generik0 I reopened this as its a valid issue that we should build the next version of Cake.Npm against Cake 0.26.0 (you still should pin Cake and your addins though)
