### ISSUE TITLE
Add the ability to specify --production in NpmCiSettings

### ISSUE THREAD

**Issue by raplemie** [cake-contrib/Cake.Npm#75]
Add the ability to specify `--production` in `NpmCiSettings`

**Comment by Philo** [comment]
Hi @raplemie - I believe this is already available, see:

https://github.com/cake-contrib/Cake.Npm/blob/develop/src/Cake.Npm.Tests/Install/NpmInstallerTests.cs#L250

**Comment by Philo** [comment]
Apologies, I just noticed you are referring to `NpmCiSettings` - correct me if I'm wrong here, but I dont believe `npm ci` supports --production as installation is performed via the `package.lock.json`

**Comment by raplemie** [comment]
Hi, 
I don't know if it is a bug or a feature, but CI indeed support using the `--production` flag
(in my package, running `npm ci` installs 826 packages, and running `npm ci --production` installs only 195 packages, both commands run right after the other, so no changes to `package-lock.json`)
