### ISSUE TITLE
Missing netstandard 0.14.0

### ISSUE THREAD

**Issue by CrimsonConqueror** [cake-contrib/Cake.Npm#81]
FYI, getting the below error when running with 0.14.0 and not 0.13.0 on build server.

Could not load
...\tools\Addins\cake.npm\Cake.Npm\lib\netstandard2.0\Cake.Npm.dll (missing netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=***)
...
errors related to not having cake.npm loaded (type errors)

**Comment by pascalberger** [comment]
Which version of Cake are you using?

**Comment by CrimsonConqueror** [comment]
0.23.0.  I'm guessing an upgrade is in order there.

**Comment by pascalberger** [comment]
Cake.Npm 0.14.0 requires Cake 0.28.0. See requirements on the [release notes](https://github.com/cake-contrib/Cake.Npm/releases).

You should also pin the addin version as described [here](https://cakebuild.net/docs/tutorials/pinning-cake-version#pinning-addin-version), to not have your builds broken if an addin is updated.

**Comment by CrimsonConqueror** [comment]
Thanks. Sorry for the doh! issue to pull you away from other coding.
